### ISSUE TITLE
gradle gauge artefacts 1.7.1 and 1.7.2 are empty on https://plugins.gradle.org/m2

### ISSUE THREAD

**Issue by spyluxos** [getgauge/gauge-gradle-plugin#2]
The deployments for version 1.7.2 (and 1.7.1) on https://plugins.gradle.org/m2 failed.

- https://plugins.gradle.org/m2/gradle/plugin/com/thoughtworks/gauge/gradle/gauge-gradle-plugin/1.7.1/
- https://plugins.gradle.org/m2/gradle/plugin/com/thoughtworks/gauge/gradle/gauge-gradle-plugin/1.7.2/
- 

All artefacts are empty.

The latest one that does work is 1.4.5

e.g. messge for 1.7.1: pom file

NoSuchKeyThe specified key does not exist.gradle.plugin.com.thoughtworks.gauge.gradle/gauge-gradle-plugin/1.7.1/0be2683d3982dbd4da379e7a98dc86d28dd9a794c52954b0955fd0ba45dee55b/gauge-gradle-plugin-1.7.1.pomF62543E18335B8256tOY0oj1c3glWOgxcA6yDzrbvichJBq0dukm7WJKEHiQpc57+mZHQdoQ/7FgTlChH0RjIcyrrWg=

**Comment by gvishnutej** [comment]
@nehashri Thanks for making progress on this issue. Can you please let me know approximately when this fix would be published? This fix will unblock our team to use gauge in gradle.

**Comment by chadlwilson** [comment]
@gvishnutej The workaround is to use the old `buildscript` syntax; e.g

```
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.thoughtworks.gauge.gradle:gauge-gradle-plugin:1.7.3'
    }
}

plugins {
    id 'java'
}

apply plugin: 'gauge'
```

Currently I understand from the Gauge team that the delay is in transferring the rights to publish the plugin over from the previous maintainer to the Gauge team.

**Comment by Apoorva-GA** [comment]
@gvishnutej @chadlwilson we have released the version [1.7.3](https://plugins.gradle.org/plugin/org.gauge) to gradle portal under `gauge.org`.

Please use the latest version.

**Comment by chadlwilson** [comment]
Hi @Apoorva-GA - unfortunately there was already a `1.7.3` release of the plugin [in May of last year](https://bintray.com/manupsunny/maven/gauge-gradle-plugin/1.7.3) to Bintray.

To reduce confusion (since the latest code published does have some changes/fixes, do you think we could bump to 1.8.0 and remove the 1.7.3 version?

**Comment by chadlwilson** [comment]
I think we can close this issue now in any case - I have tested the version published and it's working great. I'll submit a PR to update the README.

**Comment by Apoorva-GA** [comment]
@chadlwilson You can try with https://bintray.com/gauge/gauge-gradle-plugin/Nightly/1.7.3-nightly-2019-05-15.

**Comment by chadlwilson** [comment]
Hi @Apoorva-GA - what I am trying to highlight is that even these `1.7.3` nightly versions are very misleading, because the previous maintainer **already released** a `1.7.3` version a year ago - he hadn't bumped the version in the repo **after** this release. So really the nightlies; and the new version published to the Gradle Plugins portal should be a different version, either `1.7.4` or `1.8.0`, for example.

This will create confusion about which issues were fixed in which version - see #31 for example, where the user is already using 1.7.3 - the old version already published to bintray by the previous maintainer.

I would suggest we change the version to `1.8.0` or even `2.0.0` because one of my merged PRs removed support for running with old JDK versions; and to create a clean cut in the versions to go along with the change in ownership/maintainer of the repo.

**Comment by Borisakov** [comment]
@chadlwilson That works! Thanks!!

**Comment by Apoorva-GA** [comment]
We have released [gauge-gradle-plugin-1.8.0](https://plugins.gradle.org/plugin/org.gauge). Please check it out.

**Comment by chadlwilson** [comment]
> We have released [gauge-gradle-plugin-1.8.0](https://plugins.gradle.org/plugin/org.gauge). Please check it out.

Thanks a lot @Apoorva-GA - working perfectly. If it were my vote, I think we can close this now. :-)

**Comment by Borisakov** [comment]
Thanks! What is new in this version?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chadlwilson** [comment]
From a features/fixes perspective and a scan through the commit log; I believe just the PRs #26 and #23 from me. Since the plugin ownership has recently changed from the previous maintainer, it takes some time to figure out how to adapt things; publish release notes; get builds going etc.
