### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [getgauge/gauge-gradle-plugin#48]
Since Guage moved to ASL 2.0 is it possible to more repo and other Guage related repositories which have not already transitioned to ASL 2.0?

**Comment by BugDiver** [comment]
@sirinath We are in the process of moving other projects to ASL 2.0. 
/cc @zabil @sriv

**Comment by chadlwilson** [comment]
Anyone know the legal basis/process on which such license changes are being made? IANAL, but my understanding of GPL3 projects is that since it's a non-compatible license and there was no specific contributor agreement allowing license change, that you would need explicit acknowledgement of all contributors, or to somehow remove their contributions.

**Comment by sriv** [comment]
@chadlwilson thanks for checking! IANAL either, but we've consulted ours :)

For some plugins, all contributors had signed the CLA and that allowed the license to be changed without explicit consent. (You'll notice some repos under `getgauge` have moved already)

In some cases, 
- there are either new contributors or 
- contributions from folks who had signed the CLA, after Gauge (the Organization) moved to DCO instead of CLA.

In such cases, we solicited explicit consent (ex: https://github.com/getgauge/Intellij-Plugin/issues/434)

There are other details that need to be worked out in certain cases., for instance, this project was originally authored by @manupsunny , who then gracefully allowed this to be moved under `getgauge`. This is different from most other projects under `getgauge` which were incubated and maintained in this org.

Looking at the [contributors for `gauge-gradle-plugin`](https://github.com/getgauge/gauge-gradle-plugin/graphs/contributors), we have the following contributors (outside `getgauge` members):

- `Vad1mo`
- `beekeep`
- `chadlwilson`
- `manupsunny`
- `manu-agoda` (seems to be another alias of `manupsunny`)

If any of the above haven't signed the Gauge CLA (which is org specific, and not repo specific IIRC, again IANAL), we'll have to get consent explicitly.

**Comment by manupsunny** [comment]
Please let me know what needs to be done from my part, always happy to help. :)

**Comment by manupsunny** [comment]
And yes, `manu-agoda` is my alias

**Comment by chadlwilson** [comment]
Thanks for the clarity @sriv - I am also happy to have my (small) contributions re-licensed under ASL 2.0.

**Comment by sriv** [comment]
@manupsunny - I've sent you an email - please check.

@Vad1mo @beekeep  - Since you've contributed to this project, could you please indicate here (as a comment) if you are ok for gauge-gradle-plugin to be moved to Apache 2.0 license from the current GPL 3.0 license? Thanks.

**Comment by Vad1mo** [comment]
Fine with me

**Comment by beekeep** [comment]
I am also fine with the move to ASL 2.0.

**Comment by manupsunny** [comment]
@sriv Already replied
